iotboard/urls.py
from django.contrib import admin
from django.urls import path
##################################
from data import views as data
from user import views as user



urlpatterns = [
    path('', data.index,name="index"),
    path('data/', data.data,name="data"),
    path('data/<pk>', data.data_detail,name="data_detail"),
    path('login/', user.login_view, name="login_view"), # login için oluşturulan url
    path('register/', user.register_view, name="register_view"), #register için oluşturulan url
    path('logout/' , user.logout_view, name="logout_view"), #rçıkış için oluşturulan url
    path('admin/', admin.site.urls),#proje ile gelen path
]

data/models.py
from django.db import models
from device.models import Device
# Create your models here.
from django.db import models

# Create your models here.
class  Data(models.Model):

    device=models.ForeignKey(Device,related_name="device_data",on_delete=models.CASCADE, name="device")

    alan1=models.CharField(max_length=20,blank=True,null=True)
    alan2=models.CharField(max_length=20, blank=True, null=True)
    alan3=models.CharField(max_length=20,blank=True,null=True)
    alan4=models.CharField(max_length=20,blank=True,null=True)
    alan5=models.CharField(max_length=20,blank=True,null=True)
    alan6=models.CharField(max_length=20,blank=True,null=True)
    alan7=models.CharField(max_length=20,blank=True,null=True)
    alan8=models.CharField(max_length=20,blank=True,null=True)

    def __str__(self):
        return self.device.isim

templates/index.html
<!doctype html>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

      <title>Anasayfa</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

      <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

          <!-- Bootstrap core CSS -->
     <link href="../../../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="login.css" rel="stylesheet">
    <link href="signup.css" rel="stylesheet">

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

        <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


    <title>Dashboard Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="../../../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="dashboard.css" rel="stylesheet">

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Navbar Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="../../../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="navbar.css" rel="stylesheet">
    <link href="navblog.css" rel="stylesheet">

  </head>


  <body>

  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="http://127.0.0.1:8000/">IoT Board</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="http://127.0.0.1:8000">Anasayfa</a></li>

      </li>
      <li><a href="http://127.0.0.1:8000/data">Data</a></li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <li><a href="http://127.0.0.1:8000/login"><span class="glyphicon glyphicon-user"></span> Giriş </a></li>
      <li><a href="http://127.0.0.1:8000/register/"><span class="glyphicon glyphicon-user"></span> Üye ol</a></li>
      <li><a href="http://127.0.0.1:8000/logout"><span class="glyphicon glyphicon-log-in"></span> Çıkış</a></li>
    </ul>

  </div>
</nav>



  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-lg-6 col-md-6 col-xs-12"  blog-main">
      <form>
      <div id="Formalanı">
          <div class="form-group">

          </div>
        <div>

          <div class="checkbox mb-3">
        </div>
        </div>
          <div>
            <label for="formGroupExampleInput2">Şehir: </label>
            <input type="text" id="sehir" class="form-control" id="formGroupExampleInput2" placeholder="Lütfen şehrinizi giriniz">
          </div>
          <div>
            <br/>
              <p> <label form="formGroupExampleInput">Açıklama: </label></p>
              <p id="acıklama"></p> <p><textarea id="yorumalanı" class="form-control" name="yorum" cols="100" rows="7" maxlength="250"  placeholder=" Açıklama alanı..."/>
              </textarea></p>
                 <div class="dropdown">
                    <button class="btn btn-primary dropdown-toggle" id="device" name="device" type="button" data-toggle="dropdown">Device
                    <span class="caret"></span></button>
                    <ul class="dropdown-menu">
                      <li><a href="#">HTML</a></li>
                      <li><a href="#">CSS</a></li>
                      <li><a href="#">JavaScript</a></li>
                    </ul>

                  </div>
              <br>
                   <br>
              <p>Alan1 <input type="label" class="form-control" id="alan1" name="alan1" maxlength="20"> </p>
              <p>Alan2 <input type="label" class="form-control" id="alan2" name="alan2" maxlength="20"> </p>
              <p>Alan3 <input type="label" class="form-control" id="alan3" name="alan3" maxlength="20"> </p>
              <p>Alan4 <input type="label" class="form-control" id="alan4" name="alan4" maxlength="20"> </p>
              <p>Alan5 <input type="label" class="form-control" id="alan5" name="alan5" maxlength="20"> </p>
              <p>Alan6 <input type="label" class="form-control" id="alan6" name="alan6" maxlength="20"> </p>
              <p>Alan7 <input type="label" class="form-control" id="alan7" name="alan7" maxlength="20"> </p>
              <p>Alan8 <input type="label" class="form-control" id="alan8" name="alan8" maxlength="20"> </p>
            </div>
        </div>
      </form>
    </div>

    <div class="hidden-xs col-lg-6 col-md-6 hidden-xs">
  <main id="metinalani" role="main">
      <div class="blog-post">
        <h2 class="blog-post-title">YARDIM!</h2>
        <p>Kanallar, bir IotBoard uygulamasının topladığı tüm verileri depolar. Her kanal, her türlü veriyi tutabilen sekiz alan, artı konum verileri için üç alan ve bir durum verileri için bir tane içerir. Bir kanalda veri topladığınızda, IotBoard uygulamalarını analiz etmek ve görselleştirmek için kullanabilirsiniz.</p>
        <hr>
        <h3 class="blog-post-title">Kanal Ayarları</h3>
        <h3 class="blog-post-title">Kanal Adı:</h3>
        IotBoard için benzersiz bir isim girin
        <li> <h3 class="blog-post-title">Açıklama : IotBoard için bir açıklamasını girin.</h3>.</li>
        <li>Nulla vitae elit libero, a pharetra augue.</li>
        <p>Cum sociis natoque penatibus et magnis <a href="#">dis parturient montes</a>, nascetur ridiculus mus. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Sed posuere consectetur est at lobortis. Cras mattis consectetur purus sit amet fermentum.</p>
        <blockquote>
          <p>Curabitur blandit tempus porttitor. <strong>Nullam quis risus eget urna mollis</strong> ornare vel eu leo. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
        </blockquote>
        <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
        <h2>Heading</h2>
        <p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.</p>
        <h3>Sub-heading</h3>
        <p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
        <pre><code>Example code block</code></pre>
        <p>Aenean lacinia bibendum nulla sed consectetur. Etiam porta sem malesuada magna mollis euismod. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
        <h3>Sub-heading</h3>
        <p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean lacinia bibendum nulla sed consectetur. Etiam porta sem malesuada magna mollis euismod. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        <ul>
          <li>Praesent commodo cursus magna, vel scelerisque nisl consectetur et.</li>
          <li>Donec id elit non mi porta gravida at eget metus.</li>
          <li>Nulla vitae elit libero, a pharetra augue.</li>
        </ul>
        <p>Donec ullamcorper nulla non metus auctor fringilla. Nulla vitae elit libero, a pharetra augue.</p>
        <ol>
          <li>Vestibulum id ligula porta felis euismod semper.</li>
          <li>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</li>
          <li>Maecenas sed diam eget risus varius blandit sit amet non magna.</li>
        </ol>
        <p>Cras mattis consectetur purus sit amet fermentum. Sed posuere consectetur est at lobortis.</p>
      </div><!-- /.blog-post -->

      <div class="blog-post">
        <h2 class="blog-post-title">Another blog post</h2>
        <p class="blog-post-meta">December 23, 2013 by <a href="#">Jacob</a></p>

        <p>Cum sociis natoque penatibus et magnis <a href="#">dis parturient montes</a>, nascetur ridiculus mus. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Sed posuere consectetur est at lobortis. Cras mattis consectetur purus sit amet fermentum.</p>
        <blockquote>
          <p>Curabitur blandit tempus porttitor. <strong>Nullam quis risus eget urna mollis</strong> ornare vel eu leo. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
        </blockquote>
        <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
        <p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.</p>
      </div><!-- /.blog-post -->

      <div class="blog-post">
        <h2 class="blog-post-title">New feature</h2>
        <p class="blog-post-meta">December 14, 2013 by <a href="#">Chris</a></p>

        <p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean lacinia bibendum nulla sed consectetur. Etiam porta sem malesuada magna mollis euismod. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        <ul>
          <li>Praesent commodo cursus magna, vel scelerisque nisl consectetur et.</li>
          <li>Donec id elit non mi porta gravida at eget metus.</li>
          <li>Nulla vitae elit libero, a pharetra augue.</li>
        </ul>
        <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
        <p>Donec ullamcorper nulla non metus auctor fringilla. Nulla vitae elit libero, a pharetra augue.</p>
      </div><!-- /.blog-post -->
  </main>
    </div><!-- /.blog-main -->

    </div>
  </div>


  </div><!-- /.row -->







    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../../../assets/js/vendor/popper.min.js"></script>
    <script src="../../../../dist/js/bootstrap.min.js"></script>

  </body>
</html>

templates/login.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">



    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>GİRİŞ SAYFASI</title>

    <!-- Bootstrap core CSS -->
     <link href="../../../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="login.css" rel="stylesheet">
    <link href="signup.css" rel="stylesheet">

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

        <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>



</head>

<div class="container">
  <div class="row">
    <div class="col-sm-4 col-md-4 col-lg-4 col-xs-4">

    </div>

  <div class="row">
    <div class="col-sm-4 col-md-4 col-lg-4 col-xs-4">


        <body class="text-center">

            <form class="form-signin" action="" method="post">{% csrf_token %}

                <img class="mb-4" src="https://getbootstrap.com/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
                <h1 class="h3 mb-3 font-weight-normal">GİRİŞ ALANI</h1>
                <label for="username" class="sr-only">Email address</label>
                <input type="email" id="username" name="username" class="form-control" placeholder="Email address" required autofocus>
                <label for="password" class="sr-only">Password</label>
                <input type="password" id="password" name="password" class="form-control" placeholder="Password" required>
                    <div class="checkbox mb-3">
                        <label>
                            <input type="checkbox" value="remember-me"> Beni hatırla
                        </label>
                        <a href="http://127.0.0.1:8000"> Kaydol</a>
                    </div>

                <button class="btn btn-lg btn-primary btn-block" type="submit">GİRİŞ</button>
                <a href="http://127.0.0.1:8000/register/"><button class="btn btn-lg btn-primary btn-block" type="button">Kayıt ol</button></a>

                <p class="mt-5 mb-3 text-muted">&copy; 2017-2018</p>
             </form>

</div>

    <div class="row">
        <div class="col-sm-4 col-md-4 col-lg-4 col-xs-4">
    </div>
  </div>
</div>


</body>
</html>

templates/register.html
<!DOCTYPE html>

<html lang="en">
<head>

  <meta charset="UTF-8">

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="../../../../favicon.ico">


        <!-- Bootstrap core CSS -->
    <link href="../../../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="login.css" rel="stylesheet">
    <link href="signup.css" rel="stylesheet">

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

        <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


    <title>KAYDOL</title>

  <!-- Bootstrap core CSS -->
    <link href="../../../../dist/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom styles for this template -->

    <link rel="stylesheet" type="text/css" href="signup.css">

</head>




<div class="container">
  <div class="row">
    <div class="col-sm-4 col-md-4 col-lg-4 col-xs-4">

    </div>

   <div class="row">
        <div class="col-sm-4 col-md-4 col-lg-4 col-xs-4">
            <body class="text-center">
                <form class="form-signup" action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                  <img class="mb-4" src="https://getbootstrap.com/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
                  <h1 class="h3 mb-3 font-weight-normal">KAYDOL</h1>
                  <label for="username" class="sr-only">Email address</label>
                  <input type="email" id="username" name="username" class="form-control" placeholder="Email address" required autofocus>
                  <label for="password1" class="sr-only">Password</label>
                  <input type="password" id="password1" name="password1" class="form-control" placeholder="Password" required>
                  <div class="checkbox mb-3">


                  <label for="password2" class="sr-only">Please re-enter your password</label>
                  <input type="password" id="password2" name="password2" class="form-control" placeholder="Please re-enter your password" required>

                  <div class="checkbox mb-3">


                  <input type="checkbox"  id="onay" name="onay" value="lisans-accept"><a href="http://127.0.0.1:8000/register/" onclick="kontrol()"> Lisans sözleşmesini kabul ediyorum</a>



                  </div>



                    <script type="text/javascript">
                      function kontrol()

                      {
                        console.log("kontrole girildi");
                        var inputPassword,inputPassword2,onay,text;
                        var canan=document.getElementById("onay");
                        var pass1=document.getElementById("inputPassword");
                        var pass2=document.getElementById("inputPassword2");


                        if (canan.checked==true) {

                           alert("lisansı onayladınız...");
                        }
                        else{
                          alert("lisans alanı boş bırakılamaz");


                        }

                        if(!(pass1==pass2)) {
                          alert("şifreler aynı değil...");
                          return false;

                        }

                        document.getElementById("inputPassword,inputPassword2").value;

                        return true;
                      }

                    </script>

                  <button class="btn btn-lg btn-primary btn-block" id="myCheck" type="submit"><a href="#" onclick="kontrol()">KAYDOL</a></button>
                  <p class="mt-5 mb-3 text-muted">&copy; 2017-2018</p>


                </form>

            </body>
        </div>

    <div class="row">
        <div class="col-sm-4 col-md-4 col-lg-4 col-xs-4">
    </div>
  </div>
</div>
</html>

templates/veri.html
<!doctype html>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

      <title>Anasayfa</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

      <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

          <!-- Bootstrap core CSS -->
     <link href="../../../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="login.css" rel="stylesheet">
    <link href="signup.css" rel="stylesheet">

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

        <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


    <title>Dashboard Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="../../../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="dashboard.css" rel="stylesheet">

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Navbar Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="../../../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="navbar.css" rel="stylesheet">
    <link href="navblog.css" rel="stylesheet">

  </head>


  <body>

  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="http://127.0.0.1:8000/">IoT Board</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="http://127.0.0.1:8000">Anasayfa</a></li>

      </li>
      <li><a href="http://127.0.0.1:8000/data">Data</a></li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <li><a href="http://127.0.0.1:8000/login"><span class="glyphicon glyphicon-user"></span> Giriş </a></li>
      <li><a href="http://127.0.0.1:8000/register/"><span class="glyphicon glyphicon-user"></span> Üye ol</a></li>
      <li><a href="http://127.0.0.1:8000/logout"><span class="glyphicon glyphicon-log-in"></span> Çıkış</a></li>
    </ul>

  </div>
</nav>



  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-lg-12 col-md-12 col-xs-12"  blog-main">
      <form>
      <div id="Formalanı">

          <div class="form-group">

          </div>
        <div>

          <div class="checkbox mb-3">
        </div>
        </div>

          <div>



                 <div class="dropdown">
                    <button class="btn btn-primary dropdown-toggle" id="id_device" name="id_device" type="button" data-toggle="dropdown">Device
                    <span class="caret"></span></button>
                    <ul class="dropdown-menu">
                      <li><a href="#">HTML</a></li>
                      <li><a href="#">CSS</a></li>
                      <li><a href="#">JavaScript</a></li>
                    </ul>

                  </div>
              <p>Alan1 <input type="label" class="form-control" id="alan1" name="alan1" maxlength="20"> </p>
              <p>Alan2 <input type="label" class="form-control" id="alan2" name="alan2" maxlength="20"> </p>
              <p>Alan3 <input type="label" class="form-control" id="alan3" name="alan3" maxlength="20"> </p>
              <p>Alan4 <input type="label" class="form-control" id="alan4" name="alan4" maxlength="20"> </p>
              <p>Alan5 <input type="label" class="form-control" id="alan5" name="alan5" maxlength="20"> </p>
              <p>Alan6 <input type="label" class="form-control" id="alan6" name="alan6" maxlength="20"> </p>
              <p>Alan7 <input type="label" class="form-control" id="alan7" name="alan7" maxlength="20"> </p>
              <p>Alan8 <input type="label" class="form-control" id="alan8" name="alan8" maxlength="20"> </p>
              <button class="btn btn-lg btn-primary btn-block" type="submit">Gönder</button>
            </div>
        </div>
      </form>
    </div>



  </div><!-- /.row -->







    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../../../assets/js/vendor/popper.min.js"></script>
    <script src="../../../../dist/js/bootstrap.min.js"></script>

  </body>
</html>